language: node_js

node_js: 8

branches:
  only:
  - master

cache:
  directories:
  - node_modules

script:
- npm test

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: npm
  email: vdsabev@gmail.com
  api_key:
    secure: mHb2lRbR6iOU3r/1YenHUcPrrIQu0bxAnwYlQORrLoaicSp4u7lIsyUAYdOVdM9xF5F9d6w39W0FvIKnfZGWhj90xPJuOC2lHb8sXQVqBhNVs6+eco6vOei/aQ00uo93v4CAondb6I+5kwvfdJTWimc2wRcA6/p34/+mEJjSf5Ihg2JvRjcU5fOPtKxo7MS+wfI0hDOV8nRaGy4jY2iKMk7yRQ9WKqHNzxz0nMra+RzGZ6l3PTtwJI4BUlYefrrtjI3gpdCsrIThr5PfYJFndq2mlsES2YPcZ/OBH2azFaQ2FTn4luvY48VDzIneBA3qtn3GY343YSbCyafClZdesC60do49wfFqSpPaA4RIbwgmLZ/RDZtBg8mrrFxZiA4g1ma+HLzCHSnZnIX6FWJLZtT1tIaOB+pydfGsE2bgS68KE9vGjJL8GiP9NJrYszLqZpIkrwX9cKqQdRrDxJpHWb6Pc4QRJ5abC1HLkX85XTYtdorNsUnYTFiuAdFkpQKsT90fG2E3242MUa1CbPbte67I3t+z7jcPbOSToDDvyJjUfPESotbjN/a96qt9k65UvRC/MZD49iJRNFpf6u3E6CwvschT8Z82hDZ071MmRDRaDybY8cZh3hIXJxiyYBiq43WylEkDIR78cLPr2IiS/qmz1xTAWTc77ujt8Y/Syeg=
  on:
    repo: cmless/cmless
