language: node_js

node_js: 8

branches:
  only:
  - master

cache:
  directories:
  - node_modules

script:
- npm test

after_success:
- bash <(curl -s https://codecov.io/bash)

deploy:
  provider: npm
  email: vdsabev@gmail.com
  api_key:
    secure: gDf05BqBwpzDVjEiQEKNWm0Vbcy4oB01EASyFdnolVZGxrcshQCVtyr64rP8MvLsrGEVmfICH0QPluLuHA/s1T4jtlFGGldPNSXFT521hnpQ+5Gv2YUDYfJvm73AC9iyj6wpUU1jHFmVxuH5KgOiHEKV6LXG6xVqv33999l/EsGA4npT2g/yWnG3M7RctR2FFKhCGN8PD+qYlDbiyrETTw7xz0zrh3pdx6LhE8PmA8NzZYTXX1kXoU8t9/+J9aOQL8nuH19EYde0A8YPYhHGxseYcyEmp9Vlqbj+jMwSft5XbPTH4DmkU4KxfNUS6tKg9DJ6oxiDAMQIlFrOWSJH+WuBQ6OOsBACed6LbR8mfEs7h9E7JY37ylT4J78adnFjVg4sTr/GOn1Hu5HBEcj7+qRpKcYhe7TJhJO9egX38Gw7ttZvhoe6jKU3UXoI4cLGC7+WNhIdHM4Ex0+6VIqRGUCH3LeglhmKq+Bf+Bignb9/rpDrip+yzMD7Gl0JQeLayhpLFd9HpgOKJzjpANpqCjm8q5bFVxo6EHy9Tld3fIabIuTWjyObMsxu8BexDYTYWAGXJpz/si2lsdouEt0HN824taxquIMUi8wlT6c2Rw4OqruyYJSw4aarLNK+lSfc1URfdTlEwpMutkkDIuUOJ+TR+1xmT2MhIYHLMBgFYVU=
  on:
    repo: cmless/cmless
